# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graftrigo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pyqtgraph as pg
import numpy as np
import matplotlib as mp
import math
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1124, 903)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(590, 420, 101, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(590, 460, 101, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(470, 420, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 460, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(510, 620, 141, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(550, 650, 31, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(530, 680, 91, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(510, 710, 111, 31))
        self.label_8.setObjectName("label_8")
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(320, 50, 501, 341))
        self.frame_5.setStyleSheet("background-color: rgb(115, 115, 115);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(70, 60, 361, 231))
        self.frame_6.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 341, 211))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(520, 520, 101, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

        self.comboBox.currentIndexChanged.connect(self.onChanged)      
        print(self.comboBox.currentIndex())
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "MIN"))
        self.label_2.setText(_translate("Dialog", "MAX"))
        self.label_5.setText(_translate("Dialog", "Jair Santiago Cubillos Blanco"))
        self.label_6.setText(_translate("Dialog", "92720"))
        self.label_7.setText(_translate("Dialog", "Universidad ECCI"))
        self.label_8.setText(_translate("Dialog", "Ingenieria mecatronica"))
        self.comboBox.setItemText(0, _translate("Dialog", "seno"))
        self.comboBox.setItemText(1, _translate("Dialog", "coseno"))
        self.comboBox.setItemText(2, _translate("Dialog", "tangente"))
        self.comboBox.setItemText(3, _translate("Dialog", "secante"))
        self.comboBox.setItemText(4, _translate("Dialog", "cosecante"))
        self.comboBox.setItemText(5, _translate("Dialog", "cotangente"))

    
    def onChanged(self, num):
        y=[]
        
        min = float(self.textEdit.toPlainText())
        if min==0:
            min=0.1
        max = float(self.textEdit_2.toPlainText())
        x=np.linspace(min,max,100)
        for i in range(0,100):
            if num == 0:
                y.append(math.sin(x[i-1]))
            elif num == 1:
                y.append(math.cos(x[i-1]))
            elif num == 2:
                y.append(math.tan(x[i-1]))
            elif num == 3:
                y.append(1/(math.sin(x[i-1])))
            elif num == 4:
                y.append(1/(math.cos(x[i-1])))
            elif num == 5:
                y.append(1/(math.tan(x[i-1])))
                
        
        
        plt1 = pg.plot(x,y)
        self.verticalLayout_3.addWidget(plt1)
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
