# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'punto5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets, uic, QtGui, QtCore
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
import cv2
import time

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    filename = None
    final_image = None
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 50, 211, 41))
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 321, 201))
        self.label_3.setStyleSheet("border: 1px solid black")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 50, 131, 41))
        self.label_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 130, 321, 201))
        self.label_4.setStyleSheet("border: 1px solid black")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 440, 161, 101))
        self.label_5.setStyleSheet("border: 1px solid black")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(240, 450, 171, 81))
        self.plainTextEdit.setStyleSheet("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.pushButton.clicked.connect(self.cargarImagen)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IMAGEN CARGADA"))
        self.label_2.setText(_translate("MainWindow", "CONTORNO"))
        self.pushButton.setText(_translate("MainWindow", "CARGAR IMG"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Jair Santiago Cubillos Blanco \n"
"92720\n"
"Universidad ECCI\n"
"Ingenieria mecatronica\n"
""))
        
    def cargarImagen(self):
        global filename
        filename = QFileDialog.getOpenFileName(filter="Image (*.*)")[0]
        imagen = cv2.imread(filename)
        self.setPhoto(imagen)
        self.contornos(imagen)
        
    def setPhoto(self, image):
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        imagen = QImage(frame, frame.shape[1], frame.shape[0], frame.strides[0], QImage.Format_RGB888)
        imagen = imagen.scaled(400, 280, Qt.KeepAspectRatio)
        self.label_3.setPixmap(QtGui.QPixmap.fromImage(imagen))
        self.label_3.setScaledContents(True)
        
    def contornos(self, image):
        blur=cv2.blur(image,(5,5))
        imgCanny = cv2.Canny(blur, 10, 50)
        frame = cv2.cvtColor(imgCanny, cv2.COLOR_BGR2RGB)
        imagen = QImage(frame, frame.shape[1], frame.shape[0], frame.strides[0], QImage.Format_RGB888)
        self.label_4.setPixmap(QtGui.QPixmap.fromImage(imagen))
        self.label_4.setScaledContents(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
