# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CALCULADORA.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import math
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1071, 751)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(370, 230, 71, 23))
        self.pushButton.setObjectName("pushButton")
        self.resta = QtWidgets.QPushButton(Dialog)
        self.resta.setGeometry(QtCore.QRect(470, 230, 71, 23))
        self.resta.setObjectName("resta")
        self.mult = QtWidgets.QPushButton(Dialog)
        self.mult.setGeometry(QtCore.QRect(370, 270, 75, 23))
        self.mult.setObjectName("mult")
        self.div = QtWidgets.QPushButton(Dialog)
        self.div.setGeometry(QtCore.QRect(470, 270, 75, 23))
        self.div.setObjectName("div")
        self.cos = QtWidgets.QPushButton(Dialog)
        self.cos.setGeometry(QtCore.QRect(470, 310, 75, 23))
        self.cos.setObjectName("cos")
        self.modulo = QtWidgets.QPushButton(Dialog)
        self.modulo.setGeometry(QtCore.QRect(570, 230, 71, 21))
        self.modulo.setObjectName("modulo")
        self.sen = QtWidgets.QPushButton(Dialog)
        self.sen.setGeometry(QtCore.QRect(570, 270, 75, 23))
        self.sen.setObjectName("sen")
        self.arcos = QtWidgets.QPushButton(Dialog)
        self.arcos.setGeometry(QtCore.QRect(570, 310, 75, 23))
        self.arcos.setObjectName("arcos")
        self.tan = QtWidgets.QPushButton(Dialog)
        self.tan.setGeometry(QtCore.QRect(370, 310, 75, 23))
        self.tan.setObjectName("tan")
        self.arcsen = QtWidgets.QPushButton(Dialog)
        self.arcsen.setGeometry(QtCore.QRect(370, 350, 75, 23))
        self.arcsen.setObjectName("arcsen")
        self.arctan = QtWidgets.QPushButton(Dialog)
        self.arctan.setGeometry(QtCore.QRect(470, 350, 75, 23))
        self.arctan.setObjectName("arctan")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(250, 100, 104, 71))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(390, 120, 61, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(490, 100, 104, 71))
        self.textEdit_3.setObjectName("textEdit_3")
        self.igual = QtWidgets.QPushButton(Dialog)
        self.igual.setGeometry(QtCore.QRect(570, 350, 71, 23))
        self.igual.setObjectName("igual")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(240, 440, 161, 101))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(600, 450, 120, 80))
        self.frame.setObjectName("frame")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(710, 100, 104, 71))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(620, 120, 51, 41))
        self.textEdit_5.setObjectName("textEdit_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.pushButton.clicked.connect(self.sumar)
        self.resta.clicked.connect(self.restar)
        self.mult.clicked.connect(self.multiplicar)
        self.div.clicked.connect(self.dividir)
        self.modulo.clicked.connect(self.opmodulo)
        self.sen.clicked.connect(self.seno)
        self.cos.clicked.connect(self.cosop)
        self.tan.clicked.connect(self.tang)
        self.arcsen.clicked.connect(self.aseno)
        self.arcos.clicked.connect(self.acosop)
        self.arctan.clicked.connect(self.atang)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "+"))
        self.resta.setText(_translate("Dialog", "-"))
        self.mult.setText(_translate("Dialog", "*"))
        self.div.setText(_translate("Dialog", "/"))
        self.cos.setText(_translate("Dialog", "COS"))
        self.modulo.setText(_translate("Dialog", "%"))
        self.sen.setText(_translate("Dialog", "SEN"))
        self.arcos.setText(_translate("Dialog", "COS^-1"))
        self.tan.setText(_translate("Dialog", "TAN"))
        self.arcsen.setText(_translate("Dialog", "SEN^-1"))
        self.arctan.setText(_translate("Dialog", "TAN^-1"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n""<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.igual.setText(_translate("Dialog", "="))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Jair Santiago Cubillos Blanco\n"
"92720\n"
"Ingenieria mecatronica\n"
"Unversidad ECCI\n"
"2024"))
        self.textEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">=</span></p></body></html>"))

    def sumar(self):
        num1 = float(self.textEdit.toPlainText())
        num2 = float(self.textEdit_3.toPlainText())
        resultado = num1+num2
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('+')
        
    def restar(self):
        num1 = float(self.textEdit.toPlainText())
        num2 = float(self.textEdit_3.toPlainText())
        resultado = num1-num2
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('-')
        
    def multiplicar(self):
        num1 = float(self.textEdit.toPlainText())
        num2 = float(self.textEdit_3.toPlainText())
        resultado = num1*num2
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('*')
        
    def dividir(self):
        num1 = float(self.textEdit.toPlainText())
        num2 = float(self.textEdit_3.toPlainText())
        resultado = num1/num2
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('/')
        
    def opmodulo(self):
        num1 = float(self.textEdit.toPlainText())
        num2 = float(self.textEdit_3.toPlainText())
        resultado = num1%num2
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('%')
        
    def seno(self):
        num2 = float(self.textEdit_3.toPlainText())
        resultado = math.sin(num2)
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('sen')
        
    def cosop(self):
        num2 = float(self.textEdit_3.toPlainText())
        resultado = math.cos(num2)
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('cos')
        
    def tang(self):
        num2 = float(self.textEdit_3.toPlainText())
        resultado = math.tan(num2)
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('tan')
        
    def aseno(self):
        num2 = float(self.textEdit_3.toPlainText())
        resultado = math.asin(num2)
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('asen')
        
    def acosop(self):
        num2 = float(self.textEdit_3.toPlainText())
        resultado = math.acos(num2)
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('acos')
        
    def atang(self):
        num2 = float(self.textEdit_3.toPlainText())
        resultado = math.atan(num2)
        self.textEdit_4.setText(str(resultado))
        self.textEdit_2.setText('atan')
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
