# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'led.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RPi.GPIO as GPIO

class Ui_MainWindow(object):
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(3,GPIO.OUT,initial=GPIO.LOW)
    GPIO.setup(5,GPIO.OUT,initial=GPIO.LOW)
    GPIO.setup(12,GPIO.OUT)
    GPIO.setup(35,GPIO.OUT)
    pi_pwm1 = GPIO.PWM(12,1000)	
    pi_pwm2 = GPIO.PWM(35,1000)	
    pi_pwm1.start(0)	
    pi_pwm2.start(0)	
    global i,j
    j=1
    i=1

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(210, 460, 161, 81))
        self.textEdit_4.setObjectName("textEdit_4")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(440, 460, 151, 81))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(110, 140, 51, 181))
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 130, 101, 51))
        self.pushButton.setStyleSheet("background-color: rgb(255, 23, 2);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 250, 101, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 23, 2);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(250, 140, 51, 181))
        self.verticalSlider_2.setMaximum(100)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.led1)
        self.pushButton_2.clicked.connect(self.led2)
        self.verticalSlider.valueChanged.connect(self.sliderl1)
        self.verticalSlider_2.valueChanged.connect(self.sliderl2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jair Santiago Cubillos Blanco 92720</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ingenieria mecatronica </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Universidad Ecci</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2024</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "led1"))
        self.pushButton_2.setText(_translate("MainWindow", "led2"))

    def led1(self):
        global i
        if i%2==0:
            GPIO.output(3,GPIO.HIGH)
            print('on')
            
        else:
            GPIO.output(3,GPIO.LOW)
            print('off')
        i=i+1

    def led2(self):
        global j
        if j%2==0:
            GPIO.output(5,GPIO.HIGH)
            print('on2')
            
        else:
            GPIO.output(5,GPIO.LOW)
            print('off2')
        j=j+1
        print(j)

        
    def sliderl1(self):
        dc1=self.verticalSlider.value()
        self.pi_pwm1.ChangeDutyCycle(dc1)

    def sliderl2(self):
        dc2=self.verticalSlider_2.value()
        self.pi_pwm2.ChangeDutyCycle(dc2) 




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
