# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pyqtgraph as pg
import numpy as np

class Ui_Dialog(object):
    i=1
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1124, 903)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(470, 480, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 520, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(470, 560, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(500, 680, 141, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(540, 710, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(520, 740, 91, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(500, 770, 111, 31))
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(600, 50, 501, 341))
        self.frame_3.setStyleSheet("background-color: rgb(115, 115, 115);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(70, 60, 361, 231))
        self.frame_4.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 50, 241, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(120, 10, 141, 16))
        self.label_9.setObjectName("label_9")
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(20, 50, 501, 341))
        self.frame_5.setStyleSheet("background-color: rgb(115, 115, 115);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(70, 60, 361, 231))
        self.frame_6.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 50, 241, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(120, 10, 141, 16))
        self.label_10.setObjectName("label_10")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(600, 480, 160, 22))
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(600, 520, 160, 22))
        self.horizontalSlider_2.setMaximum(1000)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(600, 560, 160, 22))
        self.horizontalSlider_3.setMaximum(10000)
        self.horizontalSlider_3.setSingleStep(100)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.horizontalSlider.valueChanged.connect(self.sliderv)
        self.horizontalSlider_2.valueChanged.connect(self.sliderv)
        self.horizontalSlider_3.valueChanged.connect(self.sliderv)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "VOLTAJE (V)"))
        self.label_2.setText(_translate("Dialog", "CAPACITANCIA (F)"))
        self.label_3.setText(_translate("Dialog", "RESISTENCIA (R)"))
        self.label_5.setText(_translate("Dialog", "Jair Santiago Cubillos Blanco"))
        self.label_6.setText(_translate("Dialog", "92720"))
        self.label_7.setText(_translate("Dialog", "Universidad ECCI"))
        self.label_8.setText(_translate("Dialog", "Ingenieria mecatronica"))
        self.label_9.setText(_translate("Dialog", "descarga circuito rc"))
        self.label_10.setText(_translate("Dialog", "carga circuito rc"))
        

        
    def sliderv(self):
        v=self.horizontalSlider.value()
        c=self.horizontalSlider_2.value()
        r=self.horizontalSlider_3.value()
        tau=int(r*c)
        ydesc=[]
        ycarga=[]
        t=np.linspace(0,9*tau,9*tau)      
        
        for i in range(0,9*tau):
            descarga=v * np.exp(-i/(r*c))
            carga=v * 1 - np.exp(-i/(r*c))
            ydesc.append(descarga)
            ycarga.append(carga)
            
        plt1 = pg.plot(t,ydesc)
        plt2 = pg.plot(t,ycarga)
        
        
        self.verticalLayout_2.addWidget(plt1)
        self.verticalLayout_3.addWidget(plt2)
        
        
        
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
