# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MOTORPP.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RPi.GPIO as GPIO
from time import sleep

bit1=11
bit2=13
bit3=15
bit4=29

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.setup(bit1,GPIO.OUT,initial=GPIO.LOW)
GPIO.setup(bit2,GPIO.OUT,initial=GPIO.LOW)
GPIO.setup(bit3,GPIO.OUT,initial=GPIO.LOW)
GPIO.setup(bit4,GPIO.OUT,initial=GPIO.LOW)

class Ui_MainWindow(object):




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(420, 460, 151, 81))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(190, 460, 161, 81))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 161, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 40, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(300, 30, 110, 51))
        self.textEdit.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(500, 220, 130, 51))
        self.textEdit_3.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 220, 331, 61))
        self.label_3.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.vuelta)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jair Santiago Cubillos Blanco 92720</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ingenieria mecatronica </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Universidad Ecci</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2024</p></body></html>"))
        self.label.setText(_translate("MainWindow", "NUMERO DE VUELTAS"))
        self.pushButton.setText(_translate("MainWindow", "INICIAR"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "º RECORRIDOS:"))

    
    def vuelta(self):
        def vueltapaso():
            #paso1 
            GPIO.output(bit1,GPIO.HIGH) #1
            GPIO.output(bit2,GPIO.LOW) #0
            GPIO.output(bit3,GPIO.LOW) #0
            GPIO.output(bit4,GPIO.LOW) #0
            sleep(0.01)
            #paso2
            GPIO.output(bit1,GPIO.HIGH) #1
            GPIO.output(bit2,GPIO.HIGH) #1
            GPIO.output(bit3,GPIO.LOW) #0
            GPIO.output(bit4,GPIO.LOW) #0
            sleep(0.01)
            #paso3
            GPIO.output(bit1,GPIO.LOW) #0
            GPIO.output(bit2,GPIO.HIGH) #1
            GPIO.output(bit3,GPIO.LOW) #0
            GPIO.output(bit4,GPIO.LOW) #0
            sleep(0.01)
            #paso4
            GPIO.output(bit1,GPIO.LOW) #0
            GPIO.output(bit2,GPIO.HIGH) #1
            GPIO.output(bit3,GPIO.HIGH) #1
            GPIO.output(bit4,GPIO.LOW) #0
            sleep(0.01)
            #paso5
            GPIO.output(bit1,GPIO.LOW) #0
            GPIO.output(bit2,GPIO.LOW) #0
            GPIO.output(bit3,GPIO.HIGH) #1
            GPIO.output(bit4,GPIO.LOW) #0
            sleep(0.01)
            #paso6
            GPIO.output(bit1,GPIO.LOW) #0
            GPIO.output(bit2,GPIO.LOW) #0
            GPIO.output(bit3,GPIO.HIGH) #1
            GPIO.output(bit4,GPIO.HIGH) #1
            sleep(0.01)
            #paso7
            GPIO.output(bit1,GPIO.LOW) #0
            GPIO.output(bit2,GPIO.LOW) #0
            GPIO.output(bit3,GPIO.LOW) #0
            GPIO.output(bit4,GPIO.HIGH) #1
            sleep(0.01)
            #paso8
            GPIO.output(bit1,GPIO.LOW) #1
            GPIO.output(bit2,GPIO.LOW) #0
            GPIO.output(bit3,GPIO.LOW) #0
            GPIO.output(bit4,GPIO.HIGH) #1
            sleep(0.01)



        num =  float(self.textEdit.toPlainText())
        numpasos=512*num
        j=0
        for j in range (int(numpasos)):       
            self.textEdit_3.setText(str(int(j*0.703125)))
            vueltapaso()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
